use ring::hmac;
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use std::collections::{BTreeMap, HashMap};
use std::time::{SystemTime, UNIX_EPOCH};
use uuid::Uuid;

use crate::core::error::{NyayaError, Result};

/// Maximum age of a receipt before it's considered expired (5 minutes).
const MAX_RECEIPT_AGE_MS: u64 = 5 * 60 * 1000;

/// HMAC-signed tool execution receipt.
/// Generated by the host runtime (outside WASM memory) — the agent cannot forge these.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolReceipt {
    /// Unique receipt identifier
    pub id: String,
    /// Name of the tool/ability that was executed
    pub tool_name: String,
    /// SHA-256 hash of the canonical JSON input parameters
    pub input_hash: String,
    /// SHA-256 hash of the raw output
    pub output_hash: String,
    /// Number of results extracted from output (e.g. email count)
    pub result_count: Option<u32>,
    /// Key-value facts extracted from tool output
    pub facts: HashMap<String, String>,
    /// Unix timestamp in milliseconds
    pub timestamp_ms: u64,
    /// Execution duration in milliseconds
    pub duration_ms: u64,
    /// HMAC-SHA256 signature over (id|tool_name|input_hash|output_hash|timestamp_ms|result_count|facts)
    pub signature: String,
}

/// Signing key for receipt generation. Held by the host, never exposed to WASM.
pub struct ReceiptSigner {
    key: hmac::Key,
}

impl ReceiptSigner {
    /// Create a new signer from a secret key.
    pub fn new(secret: &[u8]) -> Self {
        Self {
            key: hmac::Key::new(hmac::HMAC_SHA256, secret),
        }
    }

    /// Generate a new signer with a random key.
    pub fn generate() -> Self {
        use ring::rand::SecureRandom;
        let mut secret = [0u8; 32];
        ring::rand::SystemRandom::new()
            .fill(&mut secret)
            .expect("Failed to generate random key");
        Self::new(&secret)
    }

    /// Load a signer from a key file, or generate and persist a new one.
    /// H8: Ensures receipt HMAC keys survive restarts.
    pub fn load_or_generate(key_path: &std::path::Path) -> Self {
        if key_path.exists() {
            if let Ok(data) = std::fs::read(key_path) {
                if data.len() >= 32 {
                    tracing::info!("Loaded receipt signing key from {:?}", key_path);
                    return Self::new(&data[..32]);
                }
            }
            tracing::warn!("Invalid key file at {:?} — regenerating", key_path);
        }

        // Generate new key and persist
        use ring::rand::SecureRandom;
        let mut secret = [0u8; 32];
        ring::rand::SystemRandom::new()
            .fill(&mut secret)
            .expect("Failed to generate random key");

        // Create parent directory if needed
        if let Some(parent) = key_path.parent() {
            let _ = std::fs::create_dir_all(parent);
        }

        // Write with restricted permissions
        if let Err(e) = std::fs::write(key_path, secret) {
            tracing::warn!(
                "Failed to persist receipt key to {:?}: {} — using ephemeral key",
                key_path,
                e
            );
        } else {
            // Set file permissions to 600 (owner read/write only)
            #[cfg(unix)]
            {
                use std::os::unix::fs::PermissionsExt;
                let _ = std::fs::set_permissions(key_path, std::fs::Permissions::from_mode(0o600));
            }
            tracing::info!(
                "Generated and persisted receipt signing key to {:?}",
                key_path
            );
        }

        Self::new(&secret)
    }

    #[allow(clippy::too_many_arguments)]
    fn sign_message(
        &self,
        id: &str,
        tool_name: &str,
        input_hash: &str,
        output_hash: &str,
        timestamp_ms: u64,
        result_count: Option<u32>,
        facts: &HashMap<String, String>,
    ) -> String {
        // Use BTreeMap for deterministic key ordering in HMAC message
        let sorted_facts: BTreeMap<&String, &String> = facts.iter().collect();
        let facts_str = serde_json::to_string(&sorted_facts).unwrap_or_default();
        let rc_str = result_count.map_or("none".to_string(), |c| c.to_string());
        let message = format!(
            "{}|{}|{}|{}|{}|{}|{}",
            id, tool_name, input_hash, output_hash, timestamp_ms, rc_str, facts_str
        );
        let tag = hmac::sign(&self.key, message.as_bytes());
        hex::encode(tag.as_ref())
    }

    /// Generate a receipt for a tool execution.
    pub fn generate_receipt(
        &self,
        tool_name: &str,
        input_json: &str,
        output_bytes: &[u8],
        duration_ms: u64,
        result_count: Option<u32>,
        facts: HashMap<String, String>,
    ) -> ToolReceipt {
        let id = Uuid::new_v4().to_string();
        let input_hash = hex::encode(Sha256::digest(input_json.as_bytes()));
        let output_hash = hex::encode(Sha256::digest(output_bytes));
        let timestamp_ms = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap_or_default()
            .as_millis() as u64;

        let signature = self.sign_message(
            &id,
            tool_name,
            &input_hash,
            &output_hash,
            timestamp_ms,
            result_count,
            &facts,
        );

        ToolReceipt {
            id,
            tool_name: tool_name.to_string(),
            input_hash,
            output_hash,
            result_count,
            facts,
            timestamp_ms,
            duration_ms,
            signature,
        }
    }

    /// Verify a receipt's signature.
    pub fn verify_receipt(&self, receipt: &ToolReceipt) -> Result<bool> {
        // Check timestamp expiry first — reject stale receipts to prevent replay attacks
        let now_ms = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap_or_default()
            .as_millis() as u64;
        if now_ms.saturating_sub(receipt.timestamp_ms) > MAX_RECEIPT_AGE_MS {
            return Ok(false);
        }

        // Use BTreeMap for deterministic key ordering (must match sign_message)
        let sorted_facts: BTreeMap<&String, &String> = receipt.facts.iter().collect();
        let facts_str = serde_json::to_string(&sorted_facts).unwrap_or_default();
        let rc_str = receipt
            .result_count
            .map_or("none".to_string(), |c| c.to_string());
        let message = format!(
            "{}|{}|{}|{}|{}|{}|{}",
            receipt.id,
            receipt.tool_name,
            receipt.input_hash,
            receipt.output_hash,
            receipt.timestamp_ms,
            rc_str,
            facts_str
        );
        let sig_bytes = hex::decode(&receipt.signature)
            .map_err(|e| NyayaError::Config(format!("Invalid signature hex: {}", e)))?;
        match hmac::verify(&self.key, message.as_bytes(), &sig_bytes) {
            Ok(()) => Ok(true),
            Err(_) => Ok(false),
        }
    }
}

/// SQLite-backed receipt store.
pub struct ReceiptStore {
    conn: rusqlite::Connection,
}

impl ReceiptStore {
    pub fn open(path: &std::path::Path) -> Result<Self> {
        let conn = rusqlite::Connection::open(path)
            .map_err(|e| NyayaError::Cache(format!("Receipt DB open failed: {}", e)))?;
        conn.execute_batch(
            "CREATE TABLE IF NOT EXISTS receipts (
                id TEXT PRIMARY KEY,
                tool_name TEXT NOT NULL,
                input_hash TEXT NOT NULL,
                output_hash TEXT NOT NULL,
                result_count INTEGER,
                facts_json TEXT NOT NULL,
                timestamp_ms INTEGER NOT NULL,
                duration_ms INTEGER NOT NULL,
                signature TEXT NOT NULL
            )",
        )
        .map_err(|e| NyayaError::Cache(format!("Receipt table creation failed: {}", e)))?;
        Ok(Self { conn })
    }

    pub fn store(&self, receipt: &ToolReceipt) -> Result<()> {
        let facts_json = serde_json::to_string(&receipt.facts)?;
        self.conn
            .execute(
                "INSERT OR REPLACE INTO receipts (id, tool_name, input_hash, output_hash, result_count, facts_json, timestamp_ms, duration_ms, signature)
                 VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9)",
                rusqlite::params![
                    receipt.id,
                    receipt.tool_name,
                    receipt.input_hash,
                    receipt.output_hash,
                    receipt.result_count,
                    facts_json,
                    receipt.timestamp_ms,
                    receipt.duration_ms,
                    receipt.signature,
                ],
            )
            .map_err(|e| NyayaError::Cache(format!("Receipt store failed: {}", e)))?;
        Ok(())
    }

    pub fn lookup(&self, id: &str) -> Result<Option<ToolReceipt>> {
        let mut stmt = self
            .conn
            .prepare(
                "SELECT id, tool_name, input_hash, output_hash, result_count, facts_json, timestamp_ms, duration_ms, signature FROM receipts WHERE id = ?1",
            )
            .map_err(|e| NyayaError::Cache(format!("Receipt query failed: {}", e)))?;

        let receipt = stmt
            .query_row(rusqlite::params![id], |row| {
                let facts_json: String = row.get(5)?;
                let facts: HashMap<String, String> =
                    serde_json::from_str(&facts_json).unwrap_or_default();
                Ok(ToolReceipt {
                    id: row.get(0)?,
                    tool_name: row.get(1)?,
                    input_hash: row.get(2)?,
                    output_hash: row.get(3)?,
                    result_count: row.get(4)?,
                    facts,
                    timestamp_ms: row.get(6)?,
                    duration_ms: row.get(7)?,
                    signature: row.get(8)?,
                })
            })
            .optional()
            .map_err(|e| NyayaError::Cache(format!("Receipt lookup failed: {}", e)))?;

        Ok(receipt)
    }

    /// List all receipts for a tool, newest first.
    pub fn list_by_tool(&self, tool_name: &str, limit: u32) -> Result<Vec<ToolReceipt>> {
        let mut stmt = self
            .conn
            .prepare(
                "SELECT id, tool_name, input_hash, output_hash, result_count, facts_json, timestamp_ms, duration_ms, signature
                 FROM receipts WHERE tool_name = ?1 ORDER BY timestamp_ms DESC LIMIT ?2",
            )
            .map_err(|e| NyayaError::Cache(format!("Receipt list failed: {}", e)))?;

        let receipts = stmt
            .query_map(rusqlite::params![tool_name, limit], |row| {
                let facts_json: String = row.get(5)?;
                let facts: HashMap<String, String> =
                    serde_json::from_str(&facts_json).unwrap_or_default();
                Ok(ToolReceipt {
                    id: row.get(0)?,
                    tool_name: row.get(1)?,
                    input_hash: row.get(2)?,
                    output_hash: row.get(3)?,
                    result_count: row.get(4)?,
                    facts,
                    timestamp_ms: row.get(6)?,
                    duration_ms: row.get(7)?,
                    signature: row.get(8)?,
                })
            })
            .map_err(|e| NyayaError::Cache(format!("Receipt list failed: {}", e)))?
            .filter_map(|r| r.ok())
            .collect();

        Ok(receipts)
    }
}

// Make optional() available on query_row
use rusqlite::OptionalExtension;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_receipt_sign_verify() {
        let signer = ReceiptSigner::generate();
        let receipt = signer.generate_receipt(
            "email_search",
            r#"{"query": "from:alice"}"#,
            b"3 results found",
            150,
            Some(3),
            HashMap::from([("sender".into(), "alice".into())]),
        );

        assert!(signer.verify_receipt(&receipt).unwrap());
        assert!(!receipt.id.is_empty());
        assert_eq!(receipt.tool_name, "email_search");
        assert_eq!(receipt.result_count, Some(3));
    }

    #[test]
    fn test_tampered_receipt_fails() {
        let signer = ReceiptSigner::generate();
        let mut receipt = signer.generate_receipt(
            "email_search",
            r#"{"query": "from:alice"}"#,
            b"3 results found",
            150,
            Some(3),
            HashMap::new(),
        );

        // Tamper with result_count — now included in HMAC, so verification should fail
        receipt.result_count = Some(5);
        assert!(!signer.verify_receipt(&receipt).unwrap());
    }

    #[test]
    fn test_receipt_store_roundtrip() {
        let dir = tempfile::tempdir().unwrap();
        let db_path = dir.path().join("receipts.db");
        let store = ReceiptStore::open(&db_path).unwrap();
        let signer = ReceiptSigner::generate();

        let receipt = signer.generate_receipt(
            "weather_fetch",
            r#"{"city": "NYC"}"#,
            b"72F sunny",
            200,
            None,
            HashMap::from([("temp".into(), "72F".into())]),
        );

        store.store(&receipt).unwrap();
        let loaded = store.lookup(&receipt.id).unwrap().unwrap();
        assert_eq!(loaded.tool_name, "weather_fetch");
        assert_eq!(loaded.facts.get("temp").unwrap(), "72F");
    }
}
