use serde::{Deserialize, Serialize};

/// Target for a worker to fetch/process.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum SourceTarget {
    Url(String),
    SearchQuery(String),
    OpenAlexQuery(String),
    DuckDuckGoQuery(String),
}

/// A planned source to fetch, with priority and worker assignment.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SourcePlan {
    pub worker_type: String, // "academic", "web_crawl", "pdf", "search", "table"
    pub target: SourceTarget,
    pub priority: u8, // 0 = highest
    pub needs_auth: bool,
    pub extraction_focus: Option<String>, // what to extract from this source
}

/// Overall research plan generated by LLM from user query.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ResearchPlan {
    pub query: String,
    pub sources: Vec<SourcePlan>,
    pub synthesis_instructions: String,
    pub max_workers: usize,
}

/// Outcome of a worker execution.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum WorkerOutcome {
    Success,
    Partial { reason: String },
    Blocked(BlockReason),
}

/// Reason a worker was blocked.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum BlockReason {
    LoginRequired,
    Captcha,
    Paywall,
    RateLimited,
    Timeout,
    BotDetected,
}

/// Result returned by a worker after execution.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WorkerResult {
    pub source_plan: SourcePlan,
    pub outcome: WorkerOutcome,
    pub content: String,
    pub content_hash: String, // SipHash hex for deduplication
    pub structured_data: Option<serde_json::Value>,
    pub citations: Vec<Citation>,
    pub elapsed_ms: u64,
}

/// A citation from a worker's output.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Citation {
    pub title: String,
    pub url: Option<String>,
    pub authors: Vec<String>,
    pub date: Option<String>,
    pub snippet: Option<String>,
}

/// Trait that all worker types implement.
pub trait WorkerType: Send + Sync {
    /// Worker name (e.g., "academic", "web_crawl").
    fn name(&self) -> &str;

    /// Whether this worker can handle the given source target.
    fn can_handle(&self, target: &SourceTarget) -> bool;

    /// Maximum pages/items this worker will process per invocation.
    fn max_pages(&self) -> usize;
}

impl WorkerResult {
    /// Compute SipHash of content for deduplication.
    pub fn compute_hash(content: &str) -> String {
        use std::collections::hash_map::DefaultHasher;
        use std::hash::{Hash, Hasher};
        let mut hasher = DefaultHasher::new();
        content.hash(&mut hasher);
        format!("{:016x}", hasher.finish())
    }
}

impl std::fmt::Display for SourceTarget {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            SourceTarget::Url(u) => write!(f, "url:{}", u),
            SourceTarget::SearchQuery(q) => write!(f, "search:{}", q),
            SourceTarget::OpenAlexQuery(q) => write!(f, "openalex:{}", q),
            SourceTarget::DuckDuckGoQuery(q) => write!(f, "ddg:{}", q),
        }
    }
}

impl std::fmt::Display for WorkerOutcome {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            WorkerOutcome::Success => write!(f, "success"),
            WorkerOutcome::Partial { reason } => write!(f, "partial: {}", reason),
            WorkerOutcome::Blocked(reason) => write!(f, "blocked: {:?}", reason),
        }
    }
}

impl std::fmt::Display for BlockReason {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            BlockReason::LoginRequired => write!(f, "login_required"),
            BlockReason::Captcha => write!(f, "captcha"),
            BlockReason::Paywall => write!(f, "paywall"),
            BlockReason::RateLimited => write!(f, "rate_limited"),
            BlockReason::Timeout => write!(f, "timeout"),
            BlockReason::BotDetected => write!(f, "bot_detected"),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_source_plan_yaml_roundtrip() {
        let plan = SourcePlan {
            worker_type: "academic".into(),
            target: SourceTarget::OpenAlexQuery("quantum computing".into()),
            priority: 1,
            needs_auth: false,
            extraction_focus: Some("abstract".into()),
        };
        let yaml = serde_yaml::to_string(&plan).unwrap();
        let back: SourcePlan = serde_yaml::from_str(&yaml).unwrap();
        assert_eq!(back.worker_type, "academic");
    }

    #[test]
    fn test_worker_outcome_serialization() {
        let outcome = WorkerOutcome::Blocked(BlockReason::Captcha);
        let json = serde_json::to_string(&outcome).unwrap();
        let back: WorkerOutcome = serde_json::from_str(&json).unwrap();
        assert!(matches!(back, WorkerOutcome::Blocked(BlockReason::Captcha)));
    }

    #[test]
    fn test_block_reason_variants() {
        // All variants display correctly
        assert_eq!(format!("{}", BlockReason::LoginRequired), "login_required");
        assert_eq!(format!("{}", BlockReason::BotDetected), "bot_detected");
    }

    #[test]
    fn test_worker_result_content_hash() {
        let h1 = WorkerResult::compute_hash("hello world");
        let h2 = WorkerResult::compute_hash("hello world");
        let h3 = WorkerResult::compute_hash("different");
        assert_eq!(h1, h2);
        assert_ne!(h1, h3);
    }
}
